package com.equity.api;

import com.equity.domain.position.ExitReason;
import com.equity.domain.position.Position;
import com.equity.domain.user.UserId;
import com.equity.market.MarketDataRouter;
import com.equity.market.universe.UniverseService;
import com.equity.risk.AccountLedger;
import com.equity.risk.MarginCache;
import com.equity.strategy.ExitPolicy;
import com.equity.strategy.MomentumStrategy;
import com.equity.strategy.RejectionLog;
import com.equity.trading.PositionBook;
import com.equity.trading.PositionLifecycle;
import com.equity.user.UserAccount;
import com.equity.user.UserRegistry;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Operator controls and the read models behind them.
 *
 * <p>Arming and halting are separate verbs on purpose. Arming is routine and reversible; halting is
 * an emergency stop that bumps the user's epoch, disowning anything already in flight. Collapsing
 * them into one toggle would make the emergency path something an operator reaches for casually,
 * and the epoch bump is not free — it invalidates orders that may be about to fill.</p>
 *
 * <p>Nothing here can close a position directly. Every exit goes through the lifecycle's queue, so
 * the "flatten" button is a request like any other and cannot race the stop logic.</p>
 */
@RestController
@RequestMapping("/api")
public class TradingController {

    private static final Logger log = LoggerFactory.getLogger(TradingController.class);

    private final UserRegistry users;
    private final PositionBook positions;
    private final PositionLifecycle lifecycle;
    private final AccountLedger ledger;
    private final MarginCache margins;
    private final com.equity.trading.Reconciler reconciler;
    private final RejectionLog rejections;
    private final UniverseService universe;
    private final MarketDataRouter router;
    private final MomentumStrategy strategy;
    private final com.equity.platform.security.CurrentUser currentUser;

    public TradingController(UserRegistry users, PositionBook positions,
                             PositionLifecycle lifecycle, AccountLedger ledger,
                             MarginCache margins, com.equity.trading.Reconciler reconciler,
                             RejectionLog rejections,
                             UniverseService universe, MarketDataRouter router,
                             MomentumStrategy strategy,
                             com.equity.platform.security.CurrentUser currentUser) {
        this.currentUser = currentUser;
        this.users = users;
        this.positions = positions;
        this.lifecycle = lifecycle;
        this.ledger = ledger;
        this.margins = margins;
        this.reconciler = reconciler;
        this.rejections = rejections;
        this.universe = universe;
        this.router = router;
        this.strategy = strategy;
    }

    // ── Users ────────────────────────────────────────────────────────────────

    @GetMapping("/users")
    public List<Map<String, Object>> listUsers() {
        List<Map<String, Object>> out = new ArrayList<>();
        users.all().forEach(a -> out.add(describe(a)));
        return out;
    }

    /**
     * One user, or a placeholder if this id has never been registered.
     *
     * <p>Deliberately does <b>not</b> create. It used to, and the console polls this endpoint every
     * five seconds for whatever id is in the box — so every id ever generated by the New button
     * became a permanent account that the strategy then evaluated forever, multiplying every
     * rejection count by the number of abandoned rows. A GET must not mutate.</p>
     */
    /**
     * The signed-in account.
     *
     * <p>Every {@code /me} endpoint below reads identity from the session. The id-in-the-path
     * variants remain for an admin looking at somebody else's account, and are the only place a
     * user id is accepted from a client at all.</p>
     */
    @GetMapping("/users/me")
    public Map<String, Object> me() {
        return describe(users.ensure(currentUser.require()));
    }

    @PostMapping("/users/me/entries")
    public Map<String, Object> setMyEntries(@RequestParam("enabled") boolean enabled) {
        return setEntries(currentUser.require().toString(), enabled);
    }

    @PostMapping("/users/me/halt")
    public Map<String, Object> haltMe() {
        return halt(currentUser.require().toString());
    }

    @PostMapping("/users/me/resume")
    public Map<String, Object> resumeMe() {
        return resume(currentUser.require().toString());
    }

    @PostMapping("/users/me/flatten")
    public Map<String, Object> flattenMe() {
        return flatten(currentUser.require().toString());
    }

    @PostMapping("/users/me/clear-loss-latch")
    public Map<String, Object> clearMyLatch() {
        return clearLatch(currentUser.require().toString());
    }

    @GetMapping("/users/{userId}")
    public Map<String, Object> user(@PathVariable String userId) {
        UserId id = UserId.of(userId);
        return users.find(id).map(this::describe).orElseGet(() -> {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("userId", userId);
            m.put("registered", false);
            m.put("status", "NOT_REGISTERED");
            m.put("entriesEnabled", false);
            m.put("mayOpen", false);
            m.put("openPositions", 0);
            m.put("pendingEntries", 0);
            m.put("realisedPnl", 0.0);
            m.put("unrealisedPnl", 0.0);
            m.put("attemptsToday", 0);
            m.put("lossLatched", false);
            m.put("availableMargin", 0.0);
            m.put("maxOpenPositions", 0);
            return m;
        });
    }

    /** Routine: lets this user open positions. Exits are unaffected either way. */
    @PostMapping("/users/{userId}/entries")
    public Map<String, Object> setEntries(@PathVariable String userId,
                                          @RequestParam("enabled") boolean enabled) {
        UserAccount account = users.ensure(UserId.of(userId));
        account.setEntriesEnabled(enabled);
        log.warn("entries {} for user={}", enabled ? "ARMED" : "disarmed", userId);
        return describe(account);
    }

    /**
     * Emergency stop: blocks new entries, bumps the epoch so in-flight orders are disowned on
     * arrival, and requests an exit on everything currently held.
     */
    @PostMapping("/users/{userId}/halt")
    public Map<String, Object> halt(@PathVariable String userId) {
        UserAccount account = users.ensure(UserId.of(userId));
        long epoch = account.halt();
        lifecycle.requestExitAll(account.userId(), ExitReason.RISK_HALT, "operator halt");
        log.error("HALT for user={} — epoch now {}, {} positions queued to close",
                userId, epoch, lifecycle.queuedExits());
        return describe(account);
    }

    /** Clears a halt. Entries stay off; re-arming is a separate, deliberate act. */
    @PostMapping("/users/{userId}/resume")
    public Map<String, Object> resume(@PathVariable String userId) {
        UserAccount account = users.ensure(UserId.of(userId));
        account.resume();
        log.warn("halt cleared for user={} — entries remain disarmed", userId);
        return describe(account);
    }

    /** Closes everything without stopping the user. Used at the end of a session, or by hand. */
    @PostMapping("/users/{userId}/flatten")
    public Map<String, Object> flatten(@PathVariable String userId) {
        UserAccount account = users.ensure(UserId.of(userId));
        lifecycle.requestExitAll(account.userId(), ExitReason.MANUAL, "operator flatten");
        return Map.of("userId", userId, "queuedExits", lifecycle.queuedExits());
    }

    /**
     * Clears a daily-loss latch.
     *
     * <p>Deliberately its own endpoint rather than part of resume. Un-latching is overriding the one
     * control that stopped a losing day, and it should never happen as a side effect of something
     * else.</p>
     */
    @PostMapping("/users/{userId}/clear-loss-latch")
    public Map<String, Object> clearLatch(@PathVariable String userId) {
        UserId id = UserId.of(userId);
        ledger.clearLatch(id);
        return describe(users.ensure(id));
    }

    /**
     * Sets how this user's open positions are managed.
     *
     * <p>Per user, and changeable at runtime, because that is the only way to answer whether a
     * trailing stop helps: run it on one user against a fixed-stop user taking the same signals, and
     * compare. A setting that can only be changed by restarting cannot be tested that way.</p>
     *
     * <p>Applies to positions already open. A stop can only ever tighten, so switching trailing on
     * mid-trade cannot loosen an existing stop — and the high-water mark is recorded from entry, so
     * it does not start trailing from wherever price happens to be at the moment of the switch.</p>
     */
    @PostMapping("/users/{userId}/exit-policy")
    public Map<String, Object> setExitPolicy(
            @PathVariable String userId,
            @RequestParam(value = "breakeven", defaultValue = "false") boolean breakeven,
            @RequestParam(value = "breakevenAtR", defaultValue = "1.0") double breakevenAtR,
            @RequestParam(value = "trailing", defaultValue = "false") boolean trailing,
            @RequestParam(value = "trailingAtR", defaultValue = "1.0") double trailingAtR,
            @RequestParam(value = "trailingAtr", defaultValue = "1.5") double trailingAtrMultiple,
            @RequestParam(value = "structureExit", defaultValue = "false") boolean structureExit) {

        UserAccount account = users.ensure(UserId.of(userId));
        ExitPolicy policy = new ExitPolicy(breakeven, breakevenAtR, trailing, trailingAtR,
                trailingAtrMultiple, structureExit);
        account.setExitPolicy(policy);
        log.warn("exit policy for user={} is now {}", userId, policy);
        return describeExitPolicy(account);
    }

    @GetMapping("/users/{userId}/exit-policy")
    public Map<String, Object> exitPolicy(@PathVariable String userId) {
        return users.find(UserId.of(userId))
                .map(this::describeExitPolicy)
                .orElseGet(() -> Map.of("userId", userId, "registered", false));
    }

    private Map<String, Object> describeExitPolicy(UserAccount account) {
        ExitPolicy p = account.exitPolicy();
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("userId", account.userId().toString());
        m.put("breakevenEnabled", p.breakevenEnabled());
        m.put("breakevenArmAtR", p.breakevenArmAtR());
        m.put("trailingEnabled", p.trailingEnabled());
        m.put("trailingArmAtR", p.trailingArmAtR());
        m.put("trailingAtrMultiple", p.trailingAtrMultiple());
        m.put("structureExitEnabled", p.structureExitEnabled());
        m.put("stopsTightenedToday", lifecycle.stopsTightened());
        return m;
    }

    // ── Read models ──────────────────────────────────────────────────────────

    @GetMapping("/positions")
    public List<Map<String, Object>> positions(
            @RequestParam(value = "userId", required = false) String userId) {
        // Defaults to the signed-in account. A user id is accepted so an admin can look at another
        // account, never so a client can choose whose positions it sees by default.
        UserId id = userId == null || userId.isBlank() ? currentUser.require() : UserId.of(userId);
        List<Map<String, Object>> out = new ArrayList<>();
        for (Position p : positions.forUser(id)) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", p.id().toString());
            m.put("symbol", p.symbol());
            m.put("status", p.status().name());
            m.put("quantity", p.filledQuantity() > 0 ? p.filledQuantity() : p.quantity());
            m.put("entryPrice", p.entryPrice());
            m.put("stopPrice", p.stopPrice());
            m.put("highWaterMark", p.highWaterMark());
            m.put("reachedR", p.favourableExcursionR());
            m.put("targetPrice", p.targetPrice());
            m.put("pattern", p.pattern() == null ? null : p.pattern().name());
            m.put("openedAt", p.openedAt() == null ? null : p.openedAt().toString());
            var tick = router.lastTick(p.symbol());
            m.put("lastPrice", tick == null ? 0 : tick.lastPrice());
            m.put("unrealisedPnl", tick == null ? 0 : p.unrealisedPnl(tick.lastPrice()));
            m.put("realisedPnl", p.realisedPnl());
            m.put("exitReason", p.exitReason() == null ? null : p.exitReason().name());
            out.add(m);
        }
        return out;
    }

    /**
     * Why candidates did not become trades.
     *
     * <p>The most useful screen in the application on a day when nothing traded: it is the
     * difference between "no setups appeared" and "a limit rejected every one of them".</p>
     */
    @GetMapping("/rejections")
    public Map<String, Object> rejections(@RequestParam(value = "samples", defaultValue = "25") int samples) {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("intents", rejections.intentCount());
        m.put("shadowIntents", rejections.shadowIntentCount());
        m.put("byStage", rejections.countsByStage());
        m.put("byCondition", rejections.countsByCondition());
        m.put("recent", rejections.recentSamples(samples).stream().map(s -> {
            Map<String, Object> row = new LinkedHashMap<>();
            row.put("at", s.at().toString());
            row.put("symbol", s.symbol());
            row.put("stage", s.stage());
            row.put("condition", s.condition());
            row.put("detail", s.detail());
            return row;
        }).toList());
        return m;
    }

    @GetMapping("/universe")
    public Map<String, Object> universe() {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("subscribed", universe.subscribedSymbols().size());
        m.put("evaluatingAll", universe.isEvaluatingAll());
        m.put("evaluated", universe.discoverySet().size());
        m.put("unresolved", universe.unresolvedSymbols());
        m.put("discoverySet", universe.discoverySet().stream().sorted().toList());
        m.put("fullModeCount", universe.fullModeCount());
        m.put("ticksSeen", router.ticksSeen());
        m.put("ticksDropped", router.ticksDropped());
        return m;
    }

    /** What each user's strategy currently believes, for the symbols it is actively tracking. */
    @GetMapping("/setups")
    public List<Map<String, Object>> setups(
            @RequestParam(value = "userId", required = false) String userId) {
        UserId id = userId == null || userId.isBlank() ? currentUser.require() : UserId.of(userId);
        List<Map<String, Object>> out = new ArrayList<>();
        strategy.setupsFor(id).forEach((symbol, setup) -> {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("symbol", symbol);
            m.put("state", setup.state().name());
            m.put("pattern", setup.pattern() == null ? null : setup.pattern().name());
            m.put("triggerLevel", setup.triggerLevel());
            m.put("structureLow", setup.structureLow());
            m.put("barsInPause", setup.barsInPause());
            out.add(m);
        });
        return out;
    }

    private Map<String, Object> describe(UserAccount account) {
        UserId id = account.userId();
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("userId", id.toString());
        m.put("registered", true);
        m.put("displayName", account.user().displayName());
        m.put("status", account.status().name());
        m.put("entriesEnabled", account.entriesEnabled());
        m.put("mayOpen", account.mayOpen());
        m.put("epoch", account.epoch());
        m.put("openPositions", positions.openCount(id));
        m.put("pendingEntries", positions.pendingEntries(id).size());
        m.put("realisedPnl", ledger.realised(id));
        m.put("unrealisedPnl", positions.unrealised(id, symbol -> {
            var tick = router.lastTick(symbol);
            return tick == null ? 0 : tick.lastPrice();
        }));
        m.put("attemptsToday", ledger.attempts(id));
        m.put("lossLatched", ledger.isLatched(id));
        m.put("lossLatchReason", ledger.latchReason(id));
        m.put("availableMargin", margins.available(id));
        m.put("maxDailyLoss", account.limits().maxDailyLossRupees());
        m.put("riskPerTrade", account.limits().riskPerTradeRupees());
        m.put("maxOpenPositions", account.limits().maxOpenPositions());
        m.put("unconfirmedEntries", lifecycle.unconfirmedEntries());
        m.put("reconciliation", describeReconciliation(id));
        return m;
    }

    /**
     * What the last reconciliation pass found.
     *
     * <p>Surfaced per account rather than buried in the log because the two things it reports are
     * the ones an operator has to act on personally: an orphan the engine will not square off, and a
     * pass that could not run at all. A silent detector is not a detector.</p>
     */
    private Map<String, Object> describeReconciliation(UserId id) {
        Map<String, Object> m = new LinkedHashMap<>();
        var report = reconciler.lastReport(id).orElse(null);
        if (report == null) {
            m.put("ran", false);
            m.put("agreed", false);
            m.put("detail", "has not run yet");
            return m;
        }
        m.put("ran", true);
        m.put("at", report.at().toString());
        m.put("agreed", report.inAgreement());
        m.put("orphans", report.orphans());
        m.put("externalCloses", report.externalCloses());
        m.put("adoptedEntries", report.adoptedEntries());
        m.put("resolvedFills", report.resolvedFills());
        m.put("abandoned", report.abandoned());
        m.put("detail", report.failed());
        return m;
    }
}
